"""Re-sealing the prompt compatibility manifest.

The domain prompt is a user-managed artifact; the manifest that pins its SHA-256 is not.
Replacing that prompt — at its own default path or anywhere else — is the documented owner
workflow, so there has to be a supported way to re-attest the bytes. Without one, the only
route back to a runnable deployment is hand-editing YAML next to a hash computed out of
band, which is exactly the kind of manual step that produces a manifest nobody trusts.

Re-sealing attests **bytes, not semantics**. It records what is on disk now. It does not
read the prompt, does not check it against the deterministic policy, and never rewrites
``schema_version`` or ``policy_revision``: a manifest bound to another policy revision is
refused, not upgraded. Whether a changed prompt still means what the policy expects is a
review, and a hashing command must not be able to imply the answer.

The manifest is regenerated from one template rather than round-tripped through a YAML
loader, so the output is deterministic, keeps its explanatory header, and does not drift
into whatever key order and quoting style the serialiser happens to prefer.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from pydantic import ValidationError

from evil_duck_dendro.config import PromptConfig
from evil_duck_dendro.observability.events import PromptMetadata
from evil_duck_dendro.prompts.library import (
    DETERMINISTIC_POLICY_REVISION,
    DomainPrompt,
    PromptLibrary,
    PromptPolicyError,
    PromptPolicyManifest,
    load_domain_prompt,
    load_manifest,
    require_external_manifest,
    resolve_prompt_path,
)

#: Printed by the CLI on every re-seal, successful or dry. The command's whole risk is that
#: it looks like an approval, so it says what it is not, every time.
SEMANTIC_NOTICE = (
    "Re-sealing attests bytes, not semantic compatibility: the manifest now records the "
    "prompt bytes on disk. It does not certify that those bytes still mean what "
    f"deterministic policy {DETERMINISTIC_POLICY_REVISION} expects — that review is the "
    "owner's, and schema_version and policy_revision are never rewritten by re-sealing."
)

_HEADER = """\
# Runtime compatibility attestation for the prompt bundle.
# Deployments overriding a prompt must point EVIL_DUCK_PROMPT_MANIFEST_PATH at a matching
# manifest. Hashes attest exact bytes; they do not prove semantic equivalence.
#
# Generated by `evil-duck prompt-seal --write`; re-run it after replacing the domain prompt
# or editing a node prompt. Re-sealing rewrites hashes only — schema_version and
# policy_revision are pinned by the code that reads this file."""

#: A YAML plain scalar that needs no quoting. Anything else (a Windows path, most obviously)
#: is emitted as a JSON string, which is a valid YAML double-quoted scalar.
_PLAIN_SCALAR = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]*$")


def _yaml_scalar(value: str) -> str:
    return value if _PLAIN_SCALAR.fullmatch(value) else json.dumps(value)


def _configured_path(path: Path) -> str:
    """Record the configured path as written, in POSIX form so the file stays portable."""
    return Path(path).as_posix()


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@dataclass(frozen=True, slots=True)
class SealChange:
    """One manifest entry re-sealing would rewrite."""

    entry: str
    old: str | None
    new: str | None

    def render(self) -> str:
        return f"{self.entry}: {self.old or '(absent)'} -> {self.new or '(removed)'}"


@dataclass(frozen=True, slots=True)
class SealPlan:
    """What re-sealing would write, and what it would change. Nothing is written yet."""

    manifest_path: Path
    domain_path: Path
    node_root: Path
    current: PromptPolicyManifest
    sealed: PromptPolicyManifest
    document: str
    changes: tuple[SealChange, ...]

    @property
    def up_to_date(self) -> bool:
        """True when the manifest already attests the bytes on disk."""
        return not self.changes


def render_manifest(manifest: PromptPolicyManifest) -> str:
    """Render a manifest deterministically from the template.

    Line endings are LF and the output is written as bytes, so the same bundle produces the
    same file on every platform.
    """
    lines = [
        _HEADER,
        "",
        f'schema_version: "{manifest.schema_version}"',
        f'policy_revision: "{manifest.policy_revision}"',
        "",
        "domain_prompt:",
        f"  path: {_yaml_scalar(manifest.domain_prompt.path)}",
        f"  sha256: {manifest.domain_prompt.sha256}",
        "",
        "node_prompts:",
        f"  root: {_yaml_scalar(manifest.node_prompts.root)}",
        f'  revision: "{manifest.node_prompts.revision}"',
        "  files:",
    ]
    for item in manifest.node_prompts.files:
        lines.append(f"    - file: {_yaml_scalar(item.file)}")
        lines.append(f"      sha256: {item.sha256}")
    return "\n".join(lines) + "\n"


def _node_prompt_files(node_root: Path) -> tuple[Path, ...]:
    """The node prompts actually on disk — the manifest describes reality, not a wish list."""
    if not node_root.is_dir():
        msg = f"Node prompt root not found: {node_root}"
        raise PromptPolicyError(msg)
    paths = tuple(
        sorted(
            (path for path in node_root.iterdir() if path.is_file() and path.suffix == ".md"),
            key=lambda path: path.name,
        )
    )
    if not paths:
        msg = f"No node prompts found under {node_root}: a manifest must admit at least one."
        raise PromptPolicyError(msg)
    return paths


def _changes(current: PromptPolicyManifest, sealed: PromptPolicyManifest) -> tuple[SealChange, ...]:
    changes: list[SealChange] = []
    if current.domain_prompt.path != sealed.domain_prompt.path:
        changes.append(
            SealChange("domain prompt path", current.domain_prompt.path, sealed.domain_prompt.path)
        )
    if current.domain_prompt.sha256 != sealed.domain_prompt.sha256:
        changes.append(
            SealChange(
                f"domain prompt {sealed.domain_prompt.path}",
                current.domain_prompt.sha256,
                sealed.domain_prompt.sha256,
            )
        )
    if current.node_prompts.root != sealed.node_prompts.root:
        changes.append(
            SealChange("node prompt root", current.node_prompts.root, sealed.node_prompts.root)
        )
    before = {item.file: item.sha256 for item in current.node_prompts.files}
    after = {item.file: item.sha256 for item in sealed.node_prompts.files}
    for name in sorted(before.keys() | after.keys()):
        old = before.get(name)
        new = after.get(name)
        if old != new:
            changes.append(SealChange(f"node prompt {name}", old, new))
    return tuple(changes)


def _sealed_manifest(
    current: PromptPolicyManifest,
    *,
    config: PromptConfig,
    domain: DomainPrompt,
    node_paths: tuple[Path, ...],
    manifest_path: Path,
) -> PromptPolicyManifest:
    payload = {
        # Carried over, never recomputed. `load_manifest` validated both against the literals
        # this code supports, so copying them is what keeps re-sealing a byte-level operation.
        "schema_version": current.schema_version,
        "policy_revision": current.policy_revision,
        "domain_prompt": {
            "path": _configured_path(config.domain_prompt_path),
            "sha256": domain.sha256,
        },
        "node_prompts": {
            "root": _configured_path(config.node_prompt_root),
            # The revision names a generation of node prompts. Bumping it is an editorial
            # decision by whoever changed them, not something a hashing command may infer.
            "revision": current.node_prompts.revision,
            "files": [{"file": path.name, "sha256": _sha256(path)} for path in node_paths],
        },
    }
    try:
        return PromptPolicyManifest.model_validate(payload)
    except ValidationError as exc:
        msg = (
            f"Re-sealing {manifest_path} would produce an invalid manifest: {exc}\n"
            "Node prompt files must be kebab-case '.md' names under the configured root."
        )
        raise PromptPolicyError(msg) from exc


def plan_seal(config: PromptConfig, *, root: Path | None = None) -> SealPlan:
    """Compute the re-sealed manifest for the configured paths. Writes nothing.

    Raises ``PromptPolicyError`` when the current manifest is missing, unreadable or bound to
    a policy this code does not support, and ``DomainPromptMissingError`` when the configured
    prompt is absent. A manifest that is merely out of date is not an error — producing the
    change list for it is the point of the command.
    """
    base = (root or Path.cwd()).resolve()
    domain_path = resolve_prompt_path(base, config.domain_prompt_path)
    manifest_path = resolve_prompt_path(base, config.manifest_path)
    node_root = resolve_prompt_path(base, config.node_prompt_root)
    require_external_manifest(domain_path, manifest_path, root=base)

    current, _ = load_manifest(manifest_path)
    domain = load_domain_prompt(domain_path)
    try:
        _ = domain.text
    except UnicodeDecodeError as exc:
        msg = f"Domain prompt {domain_path} is not valid UTF-8: {exc}"
        raise PromptPolicyError(msg) from exc

    sealed = _sealed_manifest(
        current,
        config=config,
        domain=domain,
        node_paths=_node_prompt_files(node_root),
        manifest_path=manifest_path,
    )
    return SealPlan(
        manifest_path=manifest_path,
        domain_path=domain_path,
        node_root=node_root,
        current=current,
        sealed=sealed,
        document=render_manifest(sealed),
        changes=_changes(current, sealed),
    )


def apply_seal(plan: SealPlan, config: PromptConfig, *, root: Path | None = None) -> PromptMetadata:
    """Write the re-sealed manifest, then prove the bundle validates against it.

    Written as bytes: a manifest whose content depended on the platform's line-ending
    convention would be a hash that changes when nothing changed.
    """
    plan.manifest_path.parent.mkdir(parents=True, exist_ok=True)
    plan.manifest_path.write_bytes(plan.document.encode("utf-8"))
    return PromptLibrary(config, root=root).metadata()
